- name: install Mule init.d file
  template:
    src: templates/mule.service.tpl
    dest: /etc/systemd/system/mule.service
    owner: root
    group: root
    mode: 0644
  notify:
  - restart Mule service

- name: ensure Mule service started
  service:
    name: mule
    state: started
    enabled: yes