#Install jdk
- hosts: webservers
  tasks:
    - name: install OpenJDK
      ansible.builtin.shell: |
        sudo apt-get install openjdk-8-jre -y
        status=$?
        if test $status -eq 0
        then
          java -version
          exit 0
        else
          echo "java install error"
          exit 1
        fi
      args:
        executable: /bin/bash
    - name: download Mule
      get_url:
        url: https://edgaregonzalez.s3.amazonaws.com/mule-ee-distribution-standalone-4.4.0.zip
        dest: /tmp
        checksum: sha256:22e7d49a38b59254d36b6daf35685541486d173c6d45705229d5a7b214ae9942